*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Dec 26 13:12:10 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /media/xian/Work/myproject/flaskApp-LayUI/
chdir(): No such file or directory [core/uwsgi.c line 2631]
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Dec 26 13:13:56 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5111 fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x556be425db90
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "runserver.py", line 1, in <module>
    from flaskApp import app
  File "./flaskApp/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 29728)
spawned uWSGI worker 1 (pid: 29729, cores: 1)
spawned uWSGI worker 2 (pid: 29730, cores: 1)
spawned uWSGI worker 3 (pid: 29731, cores: 1)
spawned uWSGI worker 4 (pid: 29732, cores: 1)
*** Stats server enabled on 127.0.0.1:5112 fd: 18 ***
--- no python application found, check your startup logs for errors ---
--- no python application found, check your startup logs for errors ---
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Dec 26 13:28:26 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5111).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
--- no python application found, check your startup logs for errors ---
--- no python application found, check your startup logs for errors ---
--- no python application found, check your startup logs for errors ---
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Dec 26 13:37:32 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5111 fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x559334cddb90
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "runserver.py", line 1, in <module>
    from flaskApp import app
  File "./flaskApp/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 29846)
spawned uWSGI worker 1 (pid: 29847, cores: 1)
spawned uWSGI worker 2 (pid: 29848, cores: 1)
spawned uWSGI worker 3 (pid: 29849, cores: 1)
spawned uWSGI worker 4 (pid: 29850, cores: 1)
*** Stats server enabled on 127.0.0.1:5112 fd: 18 ***
--- no python application found, check your startup logs for errors ---
--- no python application found, check your startup logs for errors ---
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Dec 26 13:51:09 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5111).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
--- no python application found, check your startup logs for errors ---
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Dec 26 14:25:18 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5111 fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x557dc5461b70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x557dc5461b70 pid: 30415 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 30415)
spawned uWSGI worker 1 (pid: 30417, cores: 1)
spawned uWSGI worker 2 (pid: 30418, cores: 1)
spawned uWSGI worker 3 (pid: 30419, cores: 1)
spawned uWSGI worker 4 (pid: 30420, cores: 1)
*** Stats server enabled on 127.0.0.1:5112 fd: 18 ***
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Dec 26 14:47:36 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5111).
bind(): Address already in use [core/socket.c line 769]
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Dec 26 15:56:59 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5111 fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55ed0befab70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x55ed0befab70 pid: 3493 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3493)
spawned uWSGI worker 1 (pid: 3495, cores: 1)
spawned uWSGI worker 2 (pid: 3496, cores: 1)
spawned uWSGI worker 3 (pid: 3497, cores: 1)
spawned uWSGI worker 4 (pid: 3498, cores: 1)
*** Stats server enabled on 127.0.0.1:5112 fd: 18 ***
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.17.1 (64bit) on [Thu Dec 27 14:07:43 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5111 fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5592f9218b70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5592f9218b70 pid: 22411 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22411)
spawned uWSGI worker 1 (pid: 22413, cores: 1)
spawned uWSGI worker 2 (pid: 22414, cores: 1)
spawned uWSGI worker 3 (pid: 22415, cores: 1)
spawned uWSGI worker 4 (pid: 22416, cores: 1)
*** Stats server enabled on 127.0.0.1:5112 fd: 18 ***
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"bnm123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': 'd8f76ca8a2939f1cf0f200ef840a955e'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"bnm123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': 'd8f76ca8a2939f1cf0f200ef840a955e'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"bnm123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': 'd8f76ca8a2939f1cf0f200ef840a955e'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
*** Starting uWSGI 2.0.17.1 (64bit) on [Thu Dec 27 14:33:35 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5111).
bind(): Address already in use [core/socket.c line 769]
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"bnm123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': 'd8f76ca8a2939f1cf0f200ef840a955e'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flaskApp/main.py", line 38, in require
    return ip_module.operation(request)
  File "./flaskApp/views/login.py", line 154, in operation
    return sign_in()
  File "./flaskApp/views/login.py", line 49, in sign_in
    result = mysqldb.find_data(table_name, str_where, str_field, args)
  File "./flaskApp/my_modules/mysqldb.py", line 87, in find_data
    db.close()
AttributeError: 'str' object has no attribute 'close'
*** Starting uWSGI 2.0.17.1 (64bit) on [Thu Dec 27 14:38:11 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5111).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.17.1 (64bit) on [Thu Dec 27 14:40:23 2018] ***
compiled with version: 7.3.0 on 25 December 2018 08:03:09
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: xian
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/myproject/flaskApp-LayUI
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/myproject/flaskApp-LayUI/
your processes number limit is 15557
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5111 fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55b52bd4cb70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55b52bd4cb70 pid: 22832 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22832)
spawned uWSGI worker 1 (pid: 22834, cores: 1)
spawned uWSGI worker 2 (pid: 22835, cores: 1)
spawned uWSGI worker 3 (pid: 22836, cores: 1)
spawned uWSGI worker 4 (pid: 22837, cores: 1)
*** Stats server enabled on 127.0.0.1:5112 fd: 18 ***
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"bnm123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': 'd8f76ca8a2939f1cf0f200ef840a955e'}
select username,password from user_list where username="yuxian" and password="d8f76ca8a2939f1cf0f200ef840a955e"
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
select username,password from user_list where username="yuxian" and password="4f6e14af56733b0f443af67b36c598fd"
yuxian登录成功
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '登录', 'action=SignIn', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:40:56', 100004, '用户列表')
ImmutableMultiDict([('action', 'findData'), ('timeStamp', '1545893112860')])
select * from model_list order by level ASC, sort ASC
ImmutableMultiDict([('action', 'findData'), ('searchJson', ''), ('prePageNum', '1'), ('currPage', '1')])
select * from record_list limit 1
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData'), ('sortStr', 'time desc')])
select * from record_list order by time desc limit 10
ImmutableMultiDict([('action', 'SignOut')])
{'username': 'yuxian', 'hash': '4f6e14af56733b0f443af67b36c598fd', 'os': 'windows', 'px': '1920x1080', 'ip': '183.14.134.112'}
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '退出', 'action=SignOut', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:45:22', 100004, '用户列表')
yuxian退出成功
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
select username,password from user_list where username="yuxian" and password="4f6e14af56733b0f443af67b36c598fd"
yuxian登录成功
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '登录', 'action=SignIn', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:46:38', 100004, '用户列表')
ImmutableMultiDict([('action', 'findData'), ('timeStamp', '1545893199230')])
select * from model_list order by level ASC, sort ASC
ImmutableMultiDict([('action', 'findData'), ('searchJson', ''), ('prePageNum', '1'), ('currPage', '1')])
select * from record_list limit 1
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData'), ('sortStr', 'time desc')])
select * from record_list order by time desc limit 10
ImmutableMultiDict([('action', 'findData'), ('searchJson', ''), ('prePageNum', '1'), ('currPage', '1')])
select * from sale_list limit 1
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData')])
select * from sale_list limit 10
ImmutableMultiDict([('action', 'findData'), ('whereStr', 'id=1'), ('prePageNum', '1'), ('currPage', '1')])
select * from sale_list where id=1 limit 1
ImmutableMultiDict([('action', 'findData'), ('searchJson', ''), ('prePageNum', '1'), ('currPage', '1')])
select user_list.id, user_list.username, user_list.password, user_list.name, user_list.email, user_list.phone, user_list.sex, user_list.age, user_list.create_name, user_list.create_time, user_list.update_name, user_list.update_time, user_list.roleId, role_class.class_name as roleName from user_list LEFT JOIN role_class ON user_list.roleId = role_class.id limit 1
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData')])
select user_list.id, user_list.username, user_list.password, user_list.name, user_list.email, user_list.phone, user_list.sex, user_list.age, user_list.create_name, user_list.create_time, user_list.update_name, user_list.update_time, user_list.roleId, role_class.class_name as roleName from user_list LEFT JOIN role_class ON user_list.roleId = role_class.id limit 10
ImmutableMultiDict([('action', 'findData'), ('searchJson', '{}'), ('prePageNum', '100000'), ('currPage', '1')])
select * from role_class limit 100000
ImmutableMultiDict([('action', 'updateData'), ('whereJson', '{"username":"yuxian"}'), ('updateJson', '{"password":"bnm123"}')])
update user_list set `password`='d8f76ca8a2939f1cf0f200ef840a955e',`update_name`='yuxian',`update_time`='2018-12-27 14:47:32' where username="yuxian"
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '修改', 'change password', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:47:32', 100004, '用户列表')
ImmutableMultiDict([('action', 'SignOut')])
{'username': 'yuxian', 'hash': '4f6e14af56733b0f443af67b36c598fd', 'os': 'windows', 'px': '1920x1080', 'ip': '183.14.134.112'}
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '退出', 'action=SignOut', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:47:37', 100004, '用户列表')
yuxian退出成功
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"bnm123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': 'd8f76ca8a2939f1cf0f200ef840a955e'}
select username,password from user_list where username="yuxian" and password="d8f76ca8a2939f1cf0f200ef840a955e"
yuxian登录成功
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '登录', 'action=SignIn', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:47:42', 100004, '用户列表')
ImmutableMultiDict([('action', 'findData'), ('timeStamp', '1545893262863')])
select * from model_list order by level ASC, sort ASC
ImmutableMultiDict([('action', 'findData'), ('searchJson', ''), ('prePageNum', '1'), ('currPage', '1')])
select * from record_list limit 1
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData'), ('sortStr', 'time desc')])
select * from record_list order by time desc limit 10
ImmutableMultiDict([('action', 'findData'), ('searchJson', ''), ('prePageNum', '1'), ('currPage', '1')])
select user_list.id, user_list.username, user_list.password, user_list.name, user_list.email, user_list.phone, user_list.sex, user_list.age, user_list.create_name, user_list.create_time, user_list.update_name, user_list.update_time, user_list.roleId, role_class.class_name as roleName from user_list LEFT JOIN role_class ON user_list.roleId = role_class.id limit 1
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData')])
select user_list.id, user_list.username, user_list.password, user_list.name, user_list.email, user_list.phone, user_list.sex, user_list.age, user_list.create_name, user_list.create_time, user_list.update_name, user_list.update_time, user_list.roleId, role_class.class_name as roleName from user_list LEFT JOIN role_class ON user_list.roleId = role_class.id limit 10
ImmutableMultiDict([('action', 'findData'), ('searchJson', '{}'), ('prePageNum', '100000'), ('currPage', '1')])
select * from role_class limit 100000
ImmutableMultiDict([('action', 'findData'), ('searchJson', '{}'), ('prePageNum', '100000'), ('currPage', '1')])
select * from role_class limit 100000
ImmutableMultiDict([('action', 'updateData'), ('whereStr', 'id=5'), ('updateJson', '{"email":"1533165000@qq.com","name":"匿名","phone":"8667424618","sex":"男","age":25,"roleId":2}')])
update user_list set `email`='1533165000@qq.com',`name`='匿名',`phone`='8667424618',`sex`='男',`age`=25,`roleId`=2,`update_name`='yuxian',`update_time`='2018-12-27 14:48:09' where id=5
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '修改', "whereStr=id=5&updateJson={'email': '1533165000@qq.com', 'name': '匿名', 'phone': '8667424618', 'sex': '男', 'age': 25, 'roleId': 2, 'update_name': 'yuxian', 'update_time': '2018-12-27 14:48:09'}", 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:48:09', 100004, '用户列表')
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData')])
select user_list.id, user_list.username, user_list.password, user_list.name, user_list.email, user_list.phone, user_list.sex, user_list.age, user_list.create_name, user_list.create_time, user_list.update_name, user_list.update_time, user_list.roleId, role_class.class_name as roleName from user_list LEFT JOIN role_class ON user_list.roleId = role_class.id limit 10
ImmutableMultiDict([('action', 'SignOut')])
{'username': 'yuxian', 'hash': 'd8f76ca8a2939f1cf0f200ef840a955e', 'os': 'windows', 'px': '1920x1080', 'ip': '183.14.134.112'}
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '退出', 'action=SignOut', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:48:14', 100004, '用户列表')
yuxian退出成功
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"admin","password":"123456"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'admin', 'password': '370b95d483d1f5b61854c462decafca4'}
select username,password from user_list where username="admin" and password="370b95d483d1f5b61854c462decafca4"
admin登录成功
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('admin', 'user_list', '登录', 'action=SignIn', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:48:23', 100004, '用户列表')
ImmutableMultiDict([('action', 'findData'), ('timeStamp', '1545893303981')])
select * from model_list order by level ASC, sort ASC
ImmutableMultiDict([('action', 'findData'), ('searchJson', ''), ('prePageNum', '1'), ('currPage', '1')])
select * from record_list limit 1
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData'), ('sortStr', 'time desc')])
select * from record_list order by time desc limit 10
ImmutableMultiDict([('action', 'findData'), ('searchJson', ''), ('prePageNum', '1'), ('currPage', '1')])
select user_list.id, user_list.username, user_list.password, user_list.name, user_list.email, user_list.phone, user_list.sex, user_list.age, user_list.create_name, user_list.create_time, user_list.update_name, user_list.update_time, user_list.roleId, role_class.class_name as roleName from user_list LEFT JOIN role_class ON user_list.roleId = role_class.id limit 1
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData')])
select user_list.id, user_list.username, user_list.password, user_list.name, user_list.email, user_list.phone, user_list.sex, user_list.age, user_list.create_name, user_list.create_time, user_list.update_name, user_list.update_time, user_list.roleId, role_class.class_name as roleName from user_list LEFT JOIN role_class ON user_list.roleId = role_class.id limit 10
ImmutableMultiDict([('action', 'findData'), ('searchJson', '{}'), ('prePageNum', '100000'), ('currPage', '1')])
select * from role_class limit 100000
ImmutableMultiDict([('action', 'updateData'), ('whereStr', 'id=5'), ('updateJson', '{"email":"1533165000@qq.com","name":"匿名","phone":"8667424618","sex":"男","age":25,"roleId":1}')])
ImmutableMultiDict([('action', 'SignOut')])
{'username': 'admin', 'hash': '370b95d483d1f5b61854c462decafca4', 'os': 'windows', 'px': '1920x1080', 'ip': '183.14.134.112'}
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('admin', 'user_list', '退出', 'action=SignOut', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:48:47', 100004, '用户列表')
admin退出成功
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
select username,password from user_list where username="yuxian" and password="4f6e14af56733b0f443af67b36c598fd"
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"bnm123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': 'd8f76ca8a2939f1cf0f200ef840a955e'}
select username,password from user_list where username="yuxian" and password="d8f76ca8a2939f1cf0f200ef840a955e"
yuxian登录成功
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '登录', 'action=SignIn', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:48:57', 100004, '用户列表')
ImmutableMultiDict([('action', 'findData'), ('timeStamp', '1545893337551')])
select * from model_list order by level ASC, sort ASC
ImmutableMultiDict([('action', 'findData'), ('searchJson', ''), ('prePageNum', '1'), ('currPage', '1')])
select * from record_list limit 1
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData'), ('sortStr', 'time desc')])
select * from record_list order by time desc limit 10
ImmutableMultiDict([('action', 'SignOut')])
{'username': 'yuxian', 'hash': 'd8f76ca8a2939f1cf0f200ef840a955e', 'os': 'windows', 'px': '1920x1080', 'ip': '183.14.134.112'}
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '退出', 'action=SignOut', 'windows', '1920x1080', '183.14.134.112', '2018-12-27 14:49:03', 100004, '用户列表')
yuxian退出成功
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"BNM123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': '4f6e14af56733b0f443af67b36c598fd'}
select username,password from user_list where username="yuxian" and password="4f6e14af56733b0f443af67b36c598fd"
ImmutableMultiDict([('action', 'SignIn'), ('whereJson', '{"username":"yuxian","password":"bnm123"}'), ('osJson', '{"os":"windows","px":"1920x1080"}')])
{'username': 'yuxian', 'password': 'd8f76ca8a2939f1cf0f200ef840a955e'}
select username,password from user_list where username="yuxian" and password="d8f76ca8a2939f1cf0f200ef840a955e"
yuxian登录成功
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '登录', 'action=SignIn', 'windows', '1920x1080', '183.14.135.9', '2018-12-28 12:59:44', 100004, '用户列表')
ImmutableMultiDict([('action', 'findData'), ('timeStamp', '1545973182580')])
select * from model_list order by level ASC, sort ASC
ImmutableMultiDict([('action', 'findData'), ('searchJson', ''), ('prePageNum', '1'), ('currPage', '1')])
select * from record_list limit 1
ImmutableMultiDict([('currPage', '1'), ('prePageNum', '10'), ('action', 'findData'), ('sortStr', 'time desc')])
select * from record_list order by time desc limit 10
ImmutableMultiDict([('action', 'SignOut')])
{'username': 'yuxian', 'hash': 'd8f76ca8a2939f1cf0f200ef840a955e', 'os': 'windows', 'px': '1920x1080', 'ip': '183.14.135.9'}
insert into record_list(`username`, `dbName`, `action`, `content`, `os`, `px`, `ip`, `time`, `modelId`, `dbName_ch`) values ('yuxian', 'user_list', '退出', 'action=SignOut', 'windows', '1920x1080', '183.14.135.9', '2018-12-28 12:59:53', 100004, '用户列表')
yuxian退出成功
*** Starting uWSGI 2.0.17.1 (64bit) on [Fri Apr  5 00:11:47 2019] ***
compiled with version: 7.3.0 on 16 December 2018 11:36:53
os: Linux-4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
nodename: dell-3576
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /media/xian/Work/myproject/flaskApp-ElementUI
writing pidfile to ./uwsgi.pid
detected binary path: /home/xian/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/myproject/flaskApp-ElementUI/
chdir(): No such file or directory [core/uwsgi.c line 2631]
